from typing import Final

INLINE_RESULTS_LIMIT: Final = 30
INLINE_QUERY_MIN_LENGTH: Final = 2
INLINE_CACHE_TIME_SECONDS: Final = 300

IMAGE_SEARCH_CACHE_TTL_SECONDS: Final = 900
FILE_ID_CACHE_TTL_SECONDS: Final = 60 * 60 * 24 * 30

MAX_DOWNLOAD_BYTES: Final = 50 * 1024 * 1024
MAX_CONCURRENT_DOWNLOADS: Final = 3
DOWNLOAD_TIMEOUT_SECONDS: Final = 120
MEDIA_GROUP_MIN_ITEMS: Final = 2
MEDIA_GROUP_MAX_ITEMS: Final = 10

STATS_TOP_LIMIT: Final = 5

VIDEO_EXTENSIONS: Final = frozenset({".mp4", ".mov", ".webm", ".mkv"})
IMAGE_EXTENSIONS: Final = frozenset({".jpg", ".jpeg", ".png", ".webp", ".gif"})
YTDLP_RETRIES: Final = 3
YTDLP_SOCKET_TIMEOUT_SECONDS: Final = 30
YTDLP_CONCURRENT_FRAGMENTS: Final = 4
CAPTION_MAX_LENGTH: Final = 200

INSTAGRAM_GRAPHQL_URL: Final = "https://www.instagram.com/graphql/query"
INSTAGRAM_POST_DOC_ID: Final = "10015901848480474"
INSTAGRAM_APP_ID: Final = "936619743392459"
INSTAGRAM_USER_AGENT: Final = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

WATCH_INTERVAL_SECONDS: Final = 1800
WATCH_FETCH_LIMIT: Final = 15
WATCH_ACCOUNT_GAP_SECONDS: Final = 5
