from typing import Final

INLINE_RESULTS_LIMIT: Final = 30
INLINE_QUERY_MIN_LENGTH: Final = 2
INLINE_CACHE_TIME_SECONDS: Final = 300

IMAGE_SEARCH_CACHE_TTL_SECONDS: Final = 900
FILE_ID_CACHE_TTL_SECONDS: Final = 60 * 60 * 24 * 30

MAX_DOWNLOAD_BYTES: Final = 50 * 1024 * 1024
MAX_CONCURRENT_DOWNLOADS: Final = 3
DOWNLOAD_TIMEOUT_SECONDS: Final = 120
MEDIA_GROUP_MIN_ITEMS: Final = 2
MEDIA_GROUP_MAX_ITEMS: Final = 10

STATS_TOP_LIMIT: Final = 5
